const numberButtons= document.querySelectorAll('[data-number]') 
const operationButtons= document.querySelectorAll('[data-operation]') 
const equalsButton= document.querySelector('[data-equals]')
const deleteButton= document.querySelector('[data-delete]')
const allclearButton= document.querySelector('[data-all-clear]')
const previousOperandTextElementButton= document.querySelector('[data-previous-operand]')
const currentOperandTextElementButton= document.querySelector('[data-current-operand]')